config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/search',   to: 'users#search'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info',  to: 'users#update_basic_info'
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances #勤怠情報を編集するページ
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances #勤怠情報を更新するページ
  resources :users do
    resources :attendances, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :attendances, dependent: :destroy #attendanceモデルと紐づけ →1対多の関係
    
    # 「remember_token」という仮想の属性を作成します。
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    
    validates :name, presence: true, length: { maximum: 50 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :department, length: { in: 3..50 }, allow_blank: true
    
    
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  
  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのため、ハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
    
  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # beforeアクション = Usersコントローラー内で定義されている全てのアクションが実行される前にbefore_actionが実行される
  # なぜbefore_actionするのか？ ⇒ログインしていないユーザーが、ユーザー情報編集や、更新を出来ないようにする為！！
  before_action :logged_in_user, only: [:index, :edit, :update]
  # editアクションとupdateアクションが実行される直前のみ、logged_in_userを実行する
  
  before_action :correct_user,   only: [:edit, :update]
  
  before_action:admin_user,      only: [:destroy, :edit_basic_info, :update_basic_info, :index]
  
  def index # 全てのユーザーを表示する
    @users = User.paginate(page: params[:page]).search(params[:search])
  end
  
  def show
    # 例) /users/1 でｱｸｾｽ時、params[:id] は 1 に置き換わる/User.find(1)になる
    @user = User.find(params[:id])
    # URLから直接ページ移動するのを防止
    redirect_to(root_url) unless @user == current_user or current_user.admin?
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
  end
  
  def new
    @user = User.new #新規作成されたUserオブジェクトをインスタンス変数に代入します
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    # @user = User.find(params[:id])  ※before_actionにてeditアクションが実行される前に@userを定義してる為、削除
  end
  
  def update
    # @user = User.find(params[:id]) ※before_actionにてudpateアクションが実行される前に@userを定義してる為、削除
    if @user.update_attributes(user_params)
          #trueの場合、属性をアップデートする = ユーザー情報を更新する
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render 'edit' # falseの場合、編集ページを再度表示する
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
    @user = User.find(params[:id])
  end
  
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user
    else
      render 'edit_basic_info'
    end
  end
  
  
  private
  
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end


    # beforeアクション
    
    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user #or current_user.admin?
    end
    
    
     # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # 基本時間などの値を、指定の書式にフォーマットして返す
  def format_basic_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
      
  <%= f.label :name, "名前" %>
  <%= f.text_field :name, class: 'form-control' %>
        
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email, class: 'form-control' %>
      
  <%= f.label :department, "所属" %>
  <%= f.text_field :department, class: 'form-control' %>
        
  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, class: 'form-control' %>
        
  <%= f.label :password_confirmation, "パスワード確認" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
        
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>  

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "基本情報編集", basic_info_path(user) %>
    | <%= link_to "削除", user, method: :delete, data: { confirm: "削除してよろしいですか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      
      <%= f.label :basic_time, "指定勤務時間" %>
      <%= f.time_field :basic_time, class: 'form-control' %>
      
      <%= f.label :work_time, "基本勤務時間" %>
      <%= f.time_field :work_time, class: 'form-control' %>
      
      <%= f.submit "編集", class: "btn btnn-primary" %>
    <% end %>  
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>

<% if params[:search].present? %>
  <h1>検索結果</h1>
<% else %>
  <h1>ユーザ一覧</h1>
<% end %>

<!--  検索拡張機能  -->
<div class="search">
  <p>ユーザー名検索</p>
    <%= form_tag(users_path, :method => 'get' ) do %>
      <div class = "input-group"> <!-- seach area ①たとえばこの二つのclassをinputっていう名前とは別の名前にして、再度CSSを指定する!! cssのdispay inline block等で試そう-->
        <%= text_field_tag :search %>
         <span class="input-group-btn"> <!-- seach area ②ここのCSSはcustom.scssのinputが指定されてる為！！-->
          <%= submit_tag '検索', :name => nil, class: "btn btn-primary" %>
         </span>
      </div>   
    <% end %>
</div>



<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<% provide(:button_text, '作成する') %>
<h1>アカウント作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month }),
                         class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %>　時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month }),
                         class: "btn btn-xs btn-primary" %>
      </td>
      <td>指定勤務時間　<%= format_basic_time(@user.work_time) %></td>
      <td>基本時間　<%= format_basic_time(@user.basic_time) %></td>
      <td>初日　<%= @first_day.to_s(:date) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締日　<%= @last_day.to_s(:date) %></td>
    </tr>
  </table>

  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>

  <table class = "table-bordered table-striped table-condensed">
    <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th rowspan = "2">日付</th>
        <th rowspan = "2">曜日</th>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td><%= day.worked_on.to_s(:date) %></td> <!--日付カラム-->
          <td>
            <% if day.worked_on.wday == 0 %>
              <span style = "color:red;">日</span>
            <% elsif day.worked_on.wday == 6 %>
              <span style = "color:blue;">土</span>
            <% else %>
              <%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>
            <% end %>  
          </td>
          <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
          <td><%= day.started_at.floor_to(15.minutes).to_s(:min) if day.started_at.present? %></td>  <!--たぶん追加機能no10ここいじれ-->
          <td>
            <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.floor_to(15.minutes).to_s(:min) if day.finished_at.present? %></td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %> <!--ここ読み込んで、合計を計算 -->
              <%= format("%.2f",(((day.finished_at.floor_to(15.minutes) - day.started_at.floor_to(15.minutes)).to_i / 60) / 60.0))  %>
              <% seconds = (day.finished_at - day.started_at).to_i %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan = "2"><%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td colspan = "6"></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>